//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 07:24:24 PM EST 
//


package prv.mark.project.soapclient.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the project.mark.prv.stocks package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: project.mark.prv.stocks
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStockPriceResponse }
     *
     */
    public GetStockPriceResponse createGetStockPriceResponse() {
        return new GetStockPriceResponse();
    }

    /**
     * Create an instance of {@link StockQuote }
     *
     */
    public StockQuote createStockQuote() {
        return new StockQuote();
    }

    /**
     * Create an instance of {@link SubmitOrderRequest }
     *
     */
    public SubmitOrderRequest createSubmitOrderRequest() {
        return new SubmitOrderRequest();
    }

    /**
     * Create an instance of {@link RequestHeader }
     *
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link StockOrder }
     *
     */
    public StockOrder createStockOrder() {
        return new StockOrder();
    }

    /**
     * Create an instance of {@link SubmitOrderResponse }
     *
     */
    public SubmitOrderResponse createSubmitOrderResponse() {
        return new SubmitOrderResponse();
    }

    /**
     * Create an instance of {@link GetStockPriceRequest }
     *
     */
    public GetStockPriceRequest createGetStockPriceRequest() {
        return new GetStockPriceRequest();
    }

}

