//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 07:24:24 PM EST 
//


package prv.mark.project.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StockQuote complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StockQuote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="statusText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tickerSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stockPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StockQuote", propOrder = {
        "statusCode",
        "statusText",
        "tickerSymbol",
        "stockPrice"
})
public class StockQuote {

    protected int statusCode;
    @XmlElement(required = true)
    protected String statusText;
    @XmlElement(required = true)
    protected String tickerSymbol;
    protected float stockPrice;

    /**
     * Gets the value of the statusCode property.
     *
     */
    public int getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     *
     */
    public void setStatusCode(int value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStatusText() {
        return statusText;
    }

    /**
     * Sets the value of the statusText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatusText(String value) {
        this.statusText = value;
    }

    /**
     * Gets the value of the tickerSymbol property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTickerSymbol() {
        return tickerSymbol;
    }

    /**
     * Sets the value of the tickerSymbol property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTickerSymbol(String value) {
        this.tickerSymbol = value;
    }

    /**
     * Gets the value of the stockPrice property.
     *
     */
    public float getStockPrice() {
        return stockPrice;
    }

    /**
     * Sets the value of the stockPrice property.
     *
     */
    public void setStockPrice(float value) {
        this.stockPrice = value;
    }

}

