-----------------------------------------------------------------------------
-- create_stock_symbol.sql
-----------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE STOCK_SYMBOL;
DROP SEQUENCE SEQ_STOCK_SYMBOL;

CREATE TABLE STOCK_SYMBOL (
  ID                  NUMBER(10,0) NOT NULL PRIMARY KEY,
  TICKER_SYMBOL       VARCHAR2(10) NOT NULL
);

CREATE UNIQUE INDEX stock_symbol_idx01 ON  STOCK_SYMBOL (TICKER_SYMBOL);

CREATE SEQUENCE SEQ_STOCK_SYMBOL
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 23667
  NOCYCLE
  CACHE 10;

INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'A');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'ABX');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'AES');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'AVGO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'AWK');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'BAC');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'BRKA');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'BRKB');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'C');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'CCI');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'CHL');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'COP');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'CSAL');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'DIS');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'DRI');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'DO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'DUK');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'EXC');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'FDX');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'FTR');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'GE');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'GIS');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'GSK');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'GWPH');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'HCP');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'IMLFF');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'KMI');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'KO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'LTC');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'MO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'NRG');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'O');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'OGE');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'OGRMF');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'PBR');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'PEGI');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'PFE');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'QQQ');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'SJT');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'SO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'T');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'UTX');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'VIV');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'VTR');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'VZ');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'X');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'XOM');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'YHOO');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'WMT');
INSERT INTO STOCK_SYMBOL (ID, TICKER_SYMBOL) VALUES (SEQ_STOCK_SYMBOL.nextval, 'Z');

COMMIT;